### ISSUE TITLE
Recommend not to use PS Prefix, it is reserved

### ISSUE THREAD

**Issue by JustinGrote** [Sam-Martin/servicenow-powershell#1]
Hey,

Would Recommend you change your prefix to SNow or PoshSNow or something like that, PS is a reserved prefix by the Powershell Team.
https://blogs.msdn.microsoft.com/powershell/2014/04/07/whats-in-a-name-using-prefixes-in-powershell/

**Comment by Sam-Martin** [comment]
Hi @JustinGrote,
Interesting! Fortunately it's just the module name and file names, rather than the variables and cmdlets, so it shouldn't be too big a change.  
Unfortunately I haven't got access to a ServiceNow installation to test this against any more, and don't want to rely solely on the unit tests.  
If you're using this module, are you up for submitting a tested PR to rename instances of PS* with POSH* by any chance?

Many thanks,

   Sam

**Comment by JustinGrote** [comment]
I'm not using the module, I was just searching around looking for good
powershell REST API usage examples and how other people are doing it. :)

**Comment by Sam-Martin** [comment]
Ah cool, well don't look at this one! It's hardly a paragon of best practice :)
Thanks for letting me know though, I'll keep this issue open in case anyone comes through and feels inclined to fix it!

**Comment by Rick-2CA** [comment]
Module rename was completed with PR #21 as discussed in Issue #17.
