### ISSUE TITLE
Get-ServiceNowIncident does not appear to include the CI name

### ISSUE THREAD

**Issue by JoeBrunsTR** [Sam-Martin/servicenow-powershell#113]
Is this project dead?  Have not seen any activity since 9/24/19.

It would appear that the Get-ServiceNowIncident does not appear to include the CI name that may or may not be defined on the INC.

Any chance we can get that?

**Comment by JoeBrunsTR** [comment]
Found it in another place

**Comment by Rick-2CA** [comment]
The two of us that were putting the most work in both got hit with other things in life.  So kinda dead, yeah, but not completely ignored.

Nothing should be hidden from a Get command if you dig under the formatting.  There can be some confusion where field names are returned with a database name so they're a tad harder to spot, but the module should be aligned with the app.  So like a Set will have a friendly name just like the UI does, but a Get will return what the field is called in their database because that's what the API delivers.
