### ISSUE TITLE
Filter on multiple fields, including state 

### ISSUE THREAD

**Issue by pckeith** [Sam-Martin/servicenow-powershell#24]
Hi, I'm using these cmdlets to pull ServiceNow Incidents and Changes for my organization. I'm able to filter on multiple fields, however cannot filter on state. Below are shown the 2 calls I used to try and filter on the state field, for both Incidents and Changes. Although I can see there is a state property returned on each line of the array ( $SNIncidents or $SNChanges), when trying to filter on it using the "state=" filter shown below, I receive the error: "You cannot call a method on a null-valued expression"

The call works fine, if I don't try to filter on state

$SNIncidents = Get-ServiceNowIncident -MatchContains @{assignment_group='My Group'; opened_at='2018'; state='New'}

$SNChanges = Get-ServiceNowChangeRequest -MatchContains @{cmdb_ci='AD Change'; assignment_group='My Group'; state='New'}

Invoke-RestMethod : The remote server returned an error: (404) Not Found.
At C:\Mypath\ServiceNow\Public\Get-ServiceNowTable.ps1:81 char:16
+ ...  $Result = (Invoke-RestMethod -Uri $Uri -Credential $ServiceNowCreden ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**You cannot call a method on a null-valued expression.**
At C:\Mypath\ServiceNow\Public\Get-ServiceNowIncident.ps1:96 char:30
+ ... ForEach-Object{$_.PSObject.TypeNames.Insert(0,"ServiceNow.Incident")}
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

**Comment by Rick-2CA** [comment]
The REST API returns a property name called 'state', however the field is called 'case_status' when performing a query.

**Comment by pckeith** [comment]
Referring to case_status doesn't break the call, however also doesn't filter the data. I got around the issue for now, by doing the following:

SNIncidents = Get-ServiceNowIncident -MatchContains @{assignment_group='My Group';opened_at='2018'}
$SNIncidents = $SNIncidents | where-Object {$_.state -ne 'Resolved'}
$SNIncidents = $SNIncidents | where-Object {$_.state -ne 'Closed'}

Now that I've gotten though this one, I need to pull information from Change Tasks, and I'm not seeing a function for that. I guess I'll file another question for that...

**Comment by Rick-2CA** [comment]
Seems I remembered incorrectly in my first reply.  You do want to use 'state' in your query, but you have to use the state codes.  For example 'Closed' is '7':

``` PowerShell
Get-ServiceNowIncident -MatchExact @{state=7} -Limit 1
```

That should get you a closed incident.  Your state list can be customized and apparently be different depending on the SNow version you started with so you'll want to see what's available on your end for other options.

The property is case sensitive.

Regarding Change Tasks - you can look at how Get-ServiceNowChangeRequest works if you dig into the function and use it as a template for a custom ChangeTask function.  Submit it as a PR and we'll get it integrated.  Otherwise it's on the "to do" list for whenever free time happens to appear out of nowhere.  :)
