### ISSUE TITLE
CMDB

### ISSUE THREAD

**Issue by MorningsWait** [Sam-Martin/servicenow-powershell#86]
Hello Team,
Can you please add support for new/get/set for servicenow CMDB as well.

**Comment by Rick-2CA** [comment]
You should be able to manipulate any table with the following commands:

```
Get-ServiceNowTableEntry
New-ServiceNowTableEntry
Remove-ServiceNowTableEntry
Update-ServiceNowTableEntry
```
In this case we're using `Update` instead of `Set` to edit an existing file.

For example the `New` command lets you specify the table name with the `Table` parameter.  Then you just hash out whatever is required with the `Values` parameter using the ServiceNow property names as the keys.  Use a `Get` on an existing item to determine formatting (like when defining a user or group calls for sys_id instead of the plain text name).
